# .github/workflows/prod-deploy.yaml
name: Prod Polybot Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 34.236.192.183
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TELEGRAM_APP_URL: prod-bot.mohammadgh.click:8443
  TELEGRAM_TOKEN: ${{ secrets.PROD_TELEGRAM_TOKEN }}

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          
          # connect to ec2 using ssh
          ssh -o StrictHostKeyChecking=accept-new -i mykey.pem ubuntu@$EC2_PUBLIC_IP "sudo systemctl restart telegram_bot_prod.service"
